name: Verify
description: Run tests and lint

runs:
  using: "composite"
  steps:
    - name: Copy env variables
      run: cp .env.example .env
      shell: bash

    - name: Lint code
      run: npm run lint:ci
      shell: bash

    - name: Run type checking
      run: npm run typecheck
      shell: bash
