name: Dependencies Audit
description: Audit the dependencies

runs:
  using: "composite"
  steps:
    - name: Audit
      run: npm audit
      continue-on-error: true
      shell: bash

    - name: Check Critical
      run: |
        critical_count=$(npm audit --audit-level=critical --json | jq '.metadata.vulnerabilities.critical')

          if [ "$critical_count" -gt 0 ]; then
            echo "::error::Critical vulnerabilities detected: $critical_count vulnerabilities found."
            exit 1
          else
            echo "No critical vulnerabilities detected."
          fi
      shell: bash
