import { LandingFooter } from "@/features/landing-page/components/landing-footer";
import { LandingHeader } from "@/features/landing-page/components/landing-header";
import { Shield } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - SubStatz",
  description:
    "Privacy Policy for SubStatz - Track and manage all your subscriptions in one place",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen flex flex-col">
      <LandingHeader />

      <main className="flex-1 container mx-auto py-12 px-4 sm:px-6 lg:px-8 max-w-4xl">
        <div className="mb-10 flex flex-col items-center text-center">
          <div className="mb-4 p-3 rounded-full bg-primary/10">
            <Shield className="h-8 w-8 text-primary" />
          </div>
          <h1 className="text-3xl font-bold sm:text-4xl md:text-5xl mb-3">
            Privacy Policy
          </h1>
          <p className="text-muted-foreground">Last updated: March 17, 2025</p>
        </div>

        <div className="bg-card border rounded-lg shadow-sm p-6 sm:p-8 md:p-10">
          <article className="prose prose-sm sm:prose lg:prose-lg mx-auto dark:prose-invert">
            <div className="not-prose mb-8 p-4 bg-primary/5 rounded-lg border border-primary/10 text-foreground">
              <p className="text-base font-medium mb-1">Your Privacy Matters</p>
              <p className="text-sm text-muted-foreground">
                This Privacy Policy describes how we collect, use, and protect
                your personal information when you use SubStatz. By using our
                service, you agree to the practices described in this policy.
              </p>
            </div>

            <div className="space-y-8">
              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="interpretation"
                >
                  1. Interpretation and Definitions
                </h2>
                <div className="mt-4 space-y-3">
                  <h3 className="text-lg font-semibold">1.1 Interpretation</h3>
                  <p>
                    The words of which the initial letter is capitalized have
                    meanings defined under the following conditions. The
                    following definitions shall have the same meaning regardless
                    of whether they appear in singular or in plural.
                  </p>

                  <h3 className="text-lg font-semibold">1.2 Definitions</h3>
                  <p>For the purposes of this Privacy Policy:</p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>
                      <span className="font-medium">Account</span> means a
                      unique account created for You to access our Service or
                      parts of our Service.
                    </li>
                    <li>
                      <span className="font-medium">Company</span> (referred to
                      as either &quot;the Company&quot;, &quot;We&quot;,
                      &quot;Us&quot; or &quot;Our&quot; in this Agreement)
                      refers to SubStatz.
                    </li>
                    <li>
                      <span className="font-medium">Personal Data</span> is any
                      information that relates to an identified or identifiable
                      individual.
                    </li>
                    <li>
                      <span className="font-medium">Service</span> refers to the
                      SubStatz application.
                    </li>
                    <li>
                      <span className="font-medium">Usage Data</span> refers to
                      data collected automatically, either generated by the use
                      of the Service or from the Service infrastructure itself.
                    </li>
                    <li>
                      <span className="font-medium">You</span> means the
                      individual accessing or using the Service, or the company,
                      or other legal entity on behalf of which such individual
                      is accessing or using the Service, as applicable.
                    </li>
                  </ul>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="data-collected"
                >
                  2. Types of Data Collected
                </h2>
                <div className="mt-4 space-y-3">
                  <h3 className="text-lg font-semibold">2.1 Personal Data</h3>
                  <p>
                    While using our Service, we ask you to provide us with
                    certain personally identifiable information that can be used
                    to contact or identify you. This includes:
                  </p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>Email address</li>
                    <li>First name and last name</li>
                  </ul>

                  <h3 className="text-lg font-semibold">2.2 Usage Data</h3>
                  <p>
                    Usage Data is collected automatically when using the
                    Service. This may include information such as your
                    device&apos;s Internet Protocol address (e.g. IP address),
                    browser type, browser version, the pages of our Service that
                    you visit, the time and date of your visit, the time spent
                    on those pages, unique device identifiers and other
                    diagnostic data.
                  </p>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="data-use"
                >
                  3. Use of Your Personal Data
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    The Company may use Personal Data for the following
                    purposes:
                  </p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>
                      <span className="font-medium">
                        To provide and maintain our Service
                      </span>
                      , including to monitor the usage of our Service.
                    </li>
                    <li>
                      <span className="font-medium">
                        To manage Your Account
                      </span>
                      : to manage Your registration as a user of the Service.
                    </li>
                    <li>
                      <span className="font-medium">To contact You</span>: To
                      contact You by email regarding updates or informative
                      communications related to the functionalities of the
                      Service.
                    </li>
                    <li>
                      <span className="font-medium">
                        To manage Your requests
                      </span>
                      : To attend and manage Your requests to Us.
                    </li>
                  </ul>

                  <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-700/30 rounded-md p-4 mt-4">
                    <p className="text-sm">
                      <span className="font-semibold">Important:</span> We do
                      not sell, rent, or trade your Personal Data with third
                      parties for their commercial purposes.
                    </p>
                  </div>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="data-retention"
                >
                  4. Retention of Your Personal Data
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    The Company will retain Your Personal Data only for as long
                    as is necessary for the purposes set out in this Privacy
                    Policy. We will retain and use Your Personal Data to the
                    extent necessary to comply with our legal obligations,
                    resolve disputes, and enforce our legal agreements and
                    policies.
                  </p>
                  <p>
                    The Company will also retain Usage Data for internal
                    analysis purposes. Usage Data is generally retained for a
                    shorter period of time, except when this data is used to
                    strengthen the security or to improve the functionality of
                    Our Service, or We are legally obligated to retain this data
                    for longer time periods.
                  </p>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="data-security"
                >
                  5. Security of Your Personal Data
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    The security of Your Personal Data is important to Us, but
                    remember that no method of transmission over the Internet,
                    or method of electronic storage is 100% secure. While We
                    strive to use commercially acceptable means to protect Your
                    Personal Data, We cannot guarantee its absolute security.
                  </p>

                  <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700/30 rounded-md p-4 mt-4">
                    <p className="text-sm">
                      We implement appropriate technical and organizational
                      measures to protect your data, including encryption,
                      secure servers, and regular security assessments.
                    </p>
                  </div>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="gdpr"
                >
                  6. GDPR Privacy Rights
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    If you are a resident of the European Union, you have
                    certain data protection rights. The Company aims to take
                    reasonable steps to allow you to correct, amend, delete, or
                    limit the use of your Personal Data.
                  </p>
                  <p>You have the following data protection rights:</p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>
                      The right to access, update or delete the information we
                      have on you.
                    </li>
                    <li>
                      The right of rectification - the right to have your
                      information corrected if it is inaccurate or incomplete.
                    </li>
                    <li>
                      The right to object to our processing of your Personal
                      Data.
                    </li>
                    <li>
                      The right of restriction - the right to request that we
                      restrict the processing of your personal information.
                    </li>
                    <li>
                      The right to data portability - the right to be provided
                      with a copy of your Personal Data in a structured,
                      machine-readable format.
                    </li>
                    <li>
                      The right to withdraw consent - the right to withdraw your
                      consent at any time where the Company relied on your
                      consent to process your personal information.
                    </li>
                  </ul>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="cookies"
                >
                  7. Cookies Policy
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    We use cookies and similar tracking technologies to track
                    the activity on our Service and store certain information.
                    These are primarily essential cookies needed for the Service
                    to function properly.
                  </p>
                  <p>
                    You can instruct your browser to refuse all cookies or to
                    indicate when a cookie is being sent. However, if you do not
                    accept cookies, you may not be able to use some portions of
                    our Service.
                  </p>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="children"
                >
                  8. Children&apos;s Privacy
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    Our Service does not address anyone under the age of 13. We
                    do not knowingly collect personally identifiable information
                    from anyone under the age of 13. If you are a parent or
                    guardian and you are aware that your child has provided us
                    with Personal Data, please contact us.
                  </p>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="changes"
                >
                  9. Changes to this Privacy Policy
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    We may update our Privacy Policy from time to time. We will
                    notify you of any changes by posting the new Privacy Policy
                    on this page and updating the &quot;Last updated&quot; date.
                  </p>
                  <p>
                    You are advised to review this Privacy Policy periodically
                    for any changes. Changes to this Privacy Policy are
                    effective when they are posted on this page.
                  </p>
                </div>
              </section>

              <section>
                <h2
                  className="text-xl font-bold text-foreground tracking-tight"
                  id="contact"
                >
                  10. Contact Us
                </h2>
                <div className="mt-4 space-y-3">
                  <p>
                    If you have any questions about this Privacy Policy, you can
                    contact us:
                  </p>
                  <p className="font-medium">
                    By email:{" "}
                    <a
                      href="mailto:support@substatz.com"
                      className="text-primary hover:text-primary/80"
                    >
                      support@substatz.com
                    </a>
                  </p>
                </div>
              </section>
            </div>

            <div className="not-prose mt-10 pt-6 border-t">
              <p className="text-sm text-muted-foreground text-center">
                This privacy policy was created to be clear and transparent
                about our data practices while complying with relevant data
                protection regulations.
              </p>
            </div>
          </article>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
