name: Deploy

on:
  workflow_run:
    workflows: ["Linting", "Type Check", "Vulnerabilities In Dependencies", "Check For Outdated Dependencies"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jaqubowsky/substatz:latest
          platforms: linux/amd64
