name: Linting

on:
  pull_request:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Setup env file
        run: cp .env.example .env

      - name: Run Linting
        run: npm run lint:ci
