name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Check Outdated Dependencies
        uses: ./.github/actions/deps-outdated

      - name: Check Critical Dependencies
        uses: ./.github/actions/deps-audit

      - name: Verify Project
        uses: ./.github/actions/verify-project
